#!/bin/sh

#origins
src=(
    ~/.cache/mozilla/firefox/h70uxj20.default
    ~/.mozilla/firefox/h70uxj20.default
)

ram=/dev/shm
dst=/run/media/$USER/Storage/.ram

IFS=
set -efu


for s in ${src[@]}
do
    r=${s////-} #unique folder name
 
    if [ ! -r $ram/$r ]; then
        mkdir -m0700 $ram/$r
    fi

    if [ -z $(readlink $s) ]; then
        mv $s $dst/$r #origin to HDD
        ln -s $ram/$r $s #create symbolic link to RAM
    fi

    #sync files in RAM and HDD
    if [ -e $s/.inram ]; then
        rsync -av --delete --exclude .inram $s/ $dst/$r
    else
        rsync -av $dst/$r/ $s/
        touch $s/.inram #origins is in RAM now
    fi
done
